# masm.py
# MIPS assembler script, utilizing SPIM assembler.
#
# Kyle Dotterrer
#	Adapted from code provided by Onur Mutlu (2015) 
# January, 2019 

import os
import sys
import argparse
import subprocess

# where is our copy of SPIM located? 
SPIM = "/usr/local/bin/spim"

# where should outputs be placed? 
HEX_DIR = "../hex/"

def main():
	# parse arguments
	parser = argparse.ArgumentParser()
	parser.add_argument("fasm", metavar="input.s", help="the MIPS assembly file (ASCII)")
	args = parser.parse_args()

	fasm = args.fasm
	fhex = os.path.splitext(args.fasm)[0] + ".x"

	# run SPIM (the actual MIPS assembler)
	cmd = [SPIM, "-asm", "-dump", "-f", fasm]
	subprocess.call(cmd)

	# rename the output text file 
	cmd = ["mv", "text.asm", fhex]
	subprocess.call(cmd)

	# and move it to the outputs directory 
	cmd = ["mv", fhex, HEX_DIR]
	subprocess.call(cmd)

	# remove all other files generated by SPIM 
	cmd = ["rm", "-f", "data.asm"]
	subprocess.call(cmd)  

	sys.exit(0)

if __name__ == "__main__":
	main()
